image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "32"
  ANDROID_BUILD_TOOLS: "32.0.0"

before_script:
  - echo MR Commit Ref Name, $CI_COMMIT_REF_SLUG
  - echo user email, $GITLAB_USER_EMAIL
  - echo Builder DIR, $CI_BUILDS_DIR
  - echo Project Name, $CI_PROJECT_NAME
  - echo Project Url, $CI_PROJECT_URL
  - echo Runner ID, $CI_RUNNER_ID
  - echo Runner Description, $CI_RUNNER_DESCRIPTION
  - echo android compile sdk, $ANDROID_COMPILE_SDK
  - echo android build tools, $ANDROID_BUILD_TOOLS
  - pwd
  - export ANDROID_HOME=~/Library/Android/sdk
  - export PATH=$PATH:~/Library/Android/sdk/platform-tools/
  - chmod +x ./gradlew

stages:
  - start
  - lint
  - compile
  - unit_test
  - deploy
  - end

when_test_start:
  stage: start
  script:
    - sh ~/2swift/CMoney/MobilePlugin/Android/CICD/BeforeScript.sh $CI_PROJECT_NAME $CI_PROJECT_URL $CI_RUNNER_ID $CI_RUNNER_DESCRIPTION $CI_COMMIT_REF_SLUG $GITLAB_USER_EMAIL
  tags:
    - mac_studio

lint_check:
  stage: lint
  script:
    - ./gradlew app:lintRelease
  artifacts:
    paths:
      - app/build/reports/
    expire_in: 2 weeks
  tags:
    - mac_studio

release_compile:
  stage: compile
  script:
    - ./gradlew app:assembleRelease
  tags:
    - mac_studio

unit_test:
  stage: unit_test
  script:
    - ./gradlew backend2:testReleaseUnitTest
    - ./gradlew koverMergedXmlReport
  tags:
    - mac_studio

deploy_to_maven:
  stage: deploy
  script:
    - ./gradlew backend2:publish
  when: on_success
  only:
    - tags
  tags:
    - mac_studio

if_test_failure:
  script:
    - sh ~/2swift/CMoney/MobilePlugin/Android/CICD/AfterScriptFailure.sh $CI_PROJECT_NAME $CI_PROJECT_URL $CI_RUNNER_ID $CI_RUNNER_DESCRIPTION $CI_COMMIT_REF_SLUG $GITLAB_USER_EMAIL
  when: on_failure
  stage: end
  tags:
    - mac_studio

after_build_success:
  script:
    - sh ~/2swift/CMoney/MobilePlugin/Android/CICD/AfterScriptSuccess.sh $CI_PROJECT_NAME $CI_PROJECT_URL $CI_RUNNER_ID $CI_RUNNER_DESCRIPTION $CI_COMMIT_REF_SLUG $GITLAB_USER_EMAIL
  when: on_success
  stage: end
  tags:
    - mac_studio
