image: openjdk:11-jdk

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.2"

before_script:
  - echo MR Commit Ref Name, $CI_COMMIT_REF_SLUG
  - echo user email, $GITLAB_USER_EMAIL
  - echo Builder DIR, $CI_BUILDS_DIR
  - echo Project Name, $CI_PROJECT_NAME
  - echo Project Url, $CI_PROJECT_URL
  - echo Runner ID, $CI_RUNNER_ID
  - echo Runner Description, $CI_RUNNER_DESCRIPTION
  - echo android compile sdk, $ANDROID_COMPILE_SDK
  - echo android build tools, $ANDROID_BUILD_TOOLS
  - pwd
  - export ANDROID_HOME=~/Library/Android/sdk
  - export PATH=$PATH:~/Library/Android/sdk/platform-tools/
  - chmod +x ./gradlew

stages:
  - lint
  - compile
  - unit_test
  - deploy

lint_check:
  stage: lint
  script:
    - ./gradlew app:lintRelease
  artifacts:
    paths:
      - app/build/reports/
    expire_in: 2 weeks

release_compile:
  stage: compile
  script:
    - ./gradlew app:assembleRelease

unit_test:
  stage: unit_test
  script:
    - ./gradlew backend2:testReleaseUnitTest
    - ./gradlew koverMergedXmlReport

deploy_to_maven:
  stage: deploy
  script:
    - ./gradlew backend2:publish
  when: on_success
  only:
    - tags