image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.3"

before_script:
  - echo MR Commit Ref Name, $CI_COMMIT_REF_SLUG
  - echo user email, $GITLAB_USER_EMAIL
  - echo Builder DIR, $CI_BUILDS_DIR
  - echo Project Name, $CI_PROJECT_NAME
  - echo Project Url, $CI_PROJECT_URL
  - echo Runner ID, $CI_RUNNER_ID
  - echo Runner Description, $CI_RUNNER_DESCRIPTION
  - pwd
  - export ANDROID_HOME=~/Library/Android/sdk
  - export PATH=$PATH:~/Library/Android/sdk/platform-tools/
  - chmod +x ./gradlew

stages:
  - reportstart
  - test
  - upload
  - reportend

startReport:
  stage: reportstart
  script:
    - sh ~/2swift/CMoney/MobilePlugin/Android/CICD/BeforeScript.sh $CI_PROJECT_NAME $CI_PROJECT_URL $CI_RUNNER_ID $CI_RUNNER_DESCRIPTION $CI_COMMIT_REF_SLUG $GITLAB_USER_EMAIL

unitTest:
  stage: test
  script: ./gradlew backend2:testReleaseUnitTest

publish_upload_githhub:
  stage: upload
  script:
#    - ./gradlew backend2:assembleRelease
    - ./gradlew backend2:publish
#    - sh ~/2swift/CMoney/MobilePlugin/Android/CICD/AarToGithub.sh AndroidBackend2Backend2 . backend2 "upload backend2 $CI_COMMIT_REF_SLUG"
  when: on_success
  only:
    - tags

if_test_failure:
  script:
    - sh ~/2swift/CMoney/MobilePlugin/Android/CICD/AfterScriptFailure.sh $CI_PROJECT_NAME $CI_PROJECT_URL $CI_RUNNER_ID $CI_RUNNER_DESCRIPTION $CI_COMMIT_REF_SLUG $GITLAB_USER_EMAIL
  when: on_failure
  stage: reportend

after_build_success:
  script:
    - sh ~/2swift/CMoney/MobilePlugin/Android/CICD/AfterScriptSuccess.sh $CI_PROJECT_NAME $CI_PROJECT_URL $CI_RUNNER_ID $CI_RUNNER_DESCRIPTION $CI_COMMIT_REF_SLUG $GITLAB_USER_EMAIL
  when: on_success
  stage: reportend
