object Versions {
    // Androidx
    const val ANDROID_TEST_CORE = "1.4.0"
    const val ANDROID_TEST_RUNNER = "1.4.0"
    const val ANDROID_TEST_RULES = "1.4.0"
    const val ANDROID_TEST_JUNIT = "1.1.3"
    const val ANDROID_TEST_TRUTH = "1.4.0"
    const val ANDROID_TEST_ARCH_CORE_TESTING = "2.1.0"
    const val ANDROID_TEST_ESPRESSO = "3.4.0"
    const val ANDROID_ROOM = "2.4.2"
    const val ANDROID_APPCOMPAT = "1.4.2"
    const val ANDROID_MATERIAL = "1.6.1"
    const val ANDROID_CONSTRAINT_LAYOUT = "2.1.4"
    const val ANDROID_RECYCLERVIEW = "1.2.1"
    const val ANDROID_ANNOTATION = "1.4.0"
    const val ANDROID_VIEWPAGER2 = "1.0.0"
    const val ANDROID_KTX_CORE = "1.8.0"
    const val ANDROID_FRAGMENT_KTX = "1.5.0"
    const val ANDROID_LIFECYCLE = "2.5.0"
    const val ANDROID_LIFECYCLE_KTX = "2.5.0"
    const val ANDROID_DOCUMENT_FILE = "1.0.1"
    const val ANDROID_EXIF_INTERFACE = "1.3.3"
    const val ANDROID_LEGACY4 = "1.0.0"
    const val ANDROID_BILLING_CLIENT = "5.0.0"
    const val ANDROID_WORK = "2.7.1"
    const val ANDROID_SWIPEREFRESHLAYOUT = "1.1.0"
    const val ANDROID_WEBKIT = "1.4.0"
    const val ANDROID_ACTIVITY_KTX = "1.5.0"
    const val ANDROIDX_NAVIGATION = "2.5.0"
    const val ANDROID_BIOMETRIC = "1.1.0"
    const val ANDROID_SECURITY = "1.0.0"
    // Android Compose
    const val ANDROID_COMPOSE = "1.2.0-rc02"
    const val ANDROID_COMPOSE_ACTIVITY = "1.5.0"
    const val ANDROID_COMPOSE_VIEW_MODEL = "2.5.0"
    const val ANDROID_COMPOSE_CONSTRAINT_LAYOUT = "1.0.1"
    // Google Play Service
    const val GOOGLE_PLAY_SERVICE_BASE = "18.1.0"
    const val GOOGLE_PLAY_SERVICE_ADS = "21.1.0"
    const val GOOGLE_PLAY_SERVICE_AUTH = "20.2.0"
    const val GOOGLE_PLAY_SERVICE_AUTH_API_PHONE = "18.0.1"
    // Firebase
    const val FIREBASE_BOM = "30.3.1"
    // JetBrains
    const val KOTLIN = "1.6.21"
    const val METADATA_JVM = "0.4.2"
    const val KSP = "1.6.21-1.0.5"
    const val KOTLIN_COMPILE_TESTING_KSP = "1.4.1"
    const val COROUTINES = "1.6.4"
    const val INTELLIJ_ANNOTATION = "12.0"
    // Test
    const val JUNIT = "4.13.2"
    const val TRUTH = "1.1.3"
    const val ROBOLECTRIC = "4.8.1"
    // TODO has new version
    const val MOCKITO = "3.12.4"
    const val MOCKK = "1.12.4"
    const val COMPILE_TESTING = "0.19"
    // Google
    const val GSON = "2.9.0"
    const val TINK_ANDROID = "1.6.1"
    const val ANDROID_BROWSER_HELPER = "2.3.0"
    const val GUAVA = "29.0-jre"
    // Internet
    const val OKHTTP = "4.10.0"
    const val OKHTTP_TESTING_SUPPORT = "3.14.9"
    const val RETROFIT = "2.9.0"
    // Log
    const val LOGGER = "2.2.0"
    const val TIMBER = "5.0.1"
    // DI
    const val KOIN = "3.2.1"
    // UI
    const val GLIDE = "4.13.2"
    const val PHOTOVIEW = "2.3.0"
    const val FLEXBOX_LAYOUT = "3.0.0"
    // TODO has new version
    const val EXOPLAYER = "2.16.1"
    const val SKELETON = "1.1.2"
    const val SHIMMERLAYOUT = "2.1.0"
    const val STRAAS = "0.23.0"
    const val MP_ANDROID_CHART = "v3.1.0"
    // Other
    const val FLURRY = "13.3.0"
    const val FACEBOOK_ANDROID = "14.1.0"
    const val CHUCKER = "3.5.2"
    const val JSOUP = "1.15.2"
    // Compiler
    const val AUTO_COMMON = "1.2.1"
    const val AUTO_VALUE_ANNOTATION = "1.9"
    const val JAVAX_ANNOTATION_API = "1.3.2"
    const val JAVAPOET = "1.13.0"
    const val KOTLINPOET = "1.10.2"
    // TODO has new version
    const val ORG_JSON = "20211205"
    const val APACHE_COMMONS_CODEC = "1.15"
    // Rx
    const val RXJAVA2 = "2.2.21"
    const val RXJAVA2_RXANDROID = "2.1.1"
    const val RXJAVA2_RXKOTLIN = "2.4.0"
    // Huawei
    const val HUAWEI_CONNECT_CORE = "1.6.0.300"
    const val HUAWEI_IAP = "5.3.0.300"
    // CMoney
    const val LOG_DATA_RECORDER = "5.4.0"
    const val CMONEY_BACKEND2 = "5.41.0"
    const val CMONEY_BROWSER = "5.0.0"
    const val CMONEY_CRM = "5.1.0-beta01"
    const val CMONEY_ANALYTICS_USER = "5.1.0"
    const val CMONEY_HUAWEI_TASK = "5.0.0"
    const val CMONEY_HUAWEI_PURCHASE = "5.0.0"
    const val CMONEY_COMMUNITY_WHITE_LIST = "5.0.0"
    const val CMONEY_COMPRESS_IMAGE = "5.0.0"
    const val CMONEY_ACCESSWEB = "5.0.0"
    const val CMONEY_REMOTECONFIG = "5.0.0"
    const val CMONEY_CRYPTO = "5.0.0"
    const val CMONEY_CORE_EXTENSION = "5.0.0"
    const val CMONEY_LOGIN = "5.0.0"
    const val CMONEY_COMMUNITY = "5.0.0"
    const val CMONEY_CHAT = "5.0.0"
    const val CMONEY_CUSTOMGROUP = "5.0.0"
    const val CMONEY_NOTIFY = "5.0.0"
    const val CMONEY_PURCHASE = "5.0.0"
    const val CMONEY_USERBEHAVIOR = "5.0.0"
    const val CMONEY_ADDITIONAL_INFORMATION = "5.0.0"
    const val CMONEY_ADDITIONAL_INFORMATION_RXJAVA = "5.0.0"
    const val CMONEY_CORE = "5.0.0-beta03"
    const val CMONEY_LOG_CORE = "5.0.0-beta02"
    const val CMONEY_MEMBER = "5.0.1"
    const val CMONEY_UTILS = "5.4.0"
}
